curators:
  DEV:
    zkHost:
    zkPath: /dev/services
  UAT:
    zkHost:
    zkPath: /uat/services
  PROD:
    zkHost:
    zkPath: /uat/services
spring:
  application:
    name: monitoring-service
  cloud:
    config:
      enabled: false
    zookeeper:
      connect-string:
      discovery:
        root: dev/services
        enabled: false
        metadata:
          management.context-path: /admin
          health.path: /ping
management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        health: /ping
      base-path: /admin
  endpoint:
    health:
      show-details: ALWAYS